package com.i2i.linkedinproject_backend.models;

/*
 * Description: This class is used to represent Guess object. @see GameSession
 * 
 * @author Arhian Albis Ramos
 */
public class Guess {
	private int index;						// The relative position of the guess object in relation to other guesses in the game session. ie: the first guess has an index of 1.
	private String guess;					// The actual user-entered guess in string form. 
	private String feedback;				// Holds the feedback generated by the GameService#generateFeedback() method. @see GameService#generateFeedback()
	
	public int getIndex() {
		return index;
	}
	
	public void setIndex(int index) {
		this.index = index;
	}
	
	public String getGuess() {
		return guess;
	}
	
	public void setGuess(String guess) {
		this.guess = guess;
	}
	
	public String getFeedback() {
		return feedback;
	}
	
	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}
	
	public Guess() {
	}
	
	public Guess(int index, String guess, String feedback) {
		this.index = index;
		this.guess = guess;
		this.feedback = feedback;
	}	
}
